version: "3.8"

services:
  main-db:
    image: mysql:8
    container_name: main-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main_db
    ports:
      - "13305:3306"
    volumes:
      - ./init/main:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  real-madrid-db:
    image: mysql:8
    container_name: real-madrid
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: real_madrid
    ports:
      - "13306:3306"
    volumes:
      - ./init/real_madrid:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  manchester-city-db:
    image: mysql:8
    container_name: manchester-city
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manchester_city
    ports:
      - "13307:3306"
    volumes:
      - ./init/manchester_city:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynamic-db-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_MAIN_URL: jdbc:mysql://main-db:3306/main_db
      SPRING_DATASOURCE_MAIN_USERNAME: root
      SPRING_DATASOURCE_MAIN_PASSWORD: root
    depends_on:
      main-db:
        condition: service_healthy
      real-madrid-db:
        condition: service_healthy
      manchester-city-db:
        condition: service_healthy
